apiVersion: v1
kind: Service
metadata:
   name: eshop-kafka
   labels:
     run: eshop-kafka
spec:
   ports:
   - port: 9092
     targetPort: 9092
     protocol: TCP
     name: kafkaport
   selector:
     run: eshop-kafka
---
apiVersion: v1
kind: Service
metadata:
   name: eshop-kafka-external
   labels:
     run: eshop-kafka-external
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafkaport
  selector:
    run: eshop-kafka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-kafka
spec:
  template:
    metadata:
      labels:
        run: eshop-kafka
    spec:
      containers:
      - name: eshop-kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
          - name: ADVERTISED_HOST
            value: "10.111.201.143"
          - name: ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_CREATE_TOPICS
            value: "SALE_NOTIFICATION_CART_TOPIC, SALE_NOTIFICATION_PRODUCT_TOPIC"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "eshop-zookeeper:2181"

