apiVersion: v1
kind: Service
metadata:
   name: eshop-payment-ms
   labels:
     run: eshop-payment-ms
spec:
   ports:
   - port: 7001
     targetPort: 7001
     protocol: TCP
   selector:
     run: eshop-payment-ms
---
apiVersion: v1
kind: Service
metadata:
   name: eshop-payment-ms-external
   labels:
     run: eshop-payment-ms-external
spec:
  type: NodePort
  ports:
  - port: 7003
    targetPort: 7003
    protocol: TCP
  selector:
    run: eshop-payment-ms
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-payment-ms
spec:
  template:
    metadata:
      labels:
        run: eshop-payment-ms
    spec:
      containers:
      - name: eshop-payment-ms
        image: apoorves/eshop-payment-ms:latest
        ports:
        - containerPort: 7003
        volumeMounts:
        - mountPath: /repos/logs
          name: payment-ms-logs-volume
        env:
          - name: PAYMENT_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: payment-ms-logs-volume
        hostPath:
          # directory location on host
          path: /mnt/sda1/repos/logs
          # this field is optional
          type: Directory